### PR TITLE
Add provisional warnings.

### PR DESCRIPTION
**Pull request by Carreau**
Last PR :-P

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
I am not sure about this one. If you initialize the interactive shell with `True` value, the `observe` handler will not be called.

**Comment by Carreau** [comment]
:-( is that true ?

**Comment by SylvainCorlay** [comment]
Well, the handler is called in case of a _change_ ...

**Comment by Carreau** [comment]
Well it does **change** from default, an it **does** work:

```
$ python -Wd -m IPython --InteractiveShell.sphinxify_docstring=True
...snip...
:root:/IPython/core/interactiveshell.py:298: ProvisionalWarning: `sphinxify_docstring` is provisional since IPython 5.0 and might change in future versions.
  warn("`sphinxify_docstring` is provisional since IPython 5.0 and might change in future versions." , ProvisionalWarning)
... snip.. 
Python 3.5.1 |Anaconda 4.0.0 (x86_64)| (default, Dec  7 2015, 11:24:55)
Type "copyright", "credits" or "license" for more information.

IPython 5.0.0.dev -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]:
```

**Pull request closed without merging**
